/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f5c39c65-cbfb-43aa-8340-e3175f53aca9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_msigQ9LTW",
    "aws_user_pools_web_client_id": "5afi12focg8b079m8ltgumakuk",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://a6rzx35z4vgobmkdfv4mzo5xyu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qmw6xdexyve7xk6cizrumnj5hq",
    "aws_user_files_s3_bucket": "amplifystoragebucket193152-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
