/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f5c39c65-cbfb-43aa-8340-e3175f53aca9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_msigQ9LTW",
    "aws_user_pools_web_client_id": "5afi12focg8b079m8ltgumakuk",
    "oauth": {}
};


export default awsmobile;
